name: Run pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        #sudo apt-get install libproj-dev proj-data proj-bin  
        #sudo apt-get install libgeos-dev 
        #sudo apt install gcc       
        #python -m pip install --upgrade pip
        #pip install Cython
        #pip install -r requirements.txt
        #python setup.py install
        #pip install pytest
        $CONDA/bin/conda env update --file spec-file.txt --name base
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest -v
