name: Run pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./.github/workflows/spec-file.txt
    - name: Run "pytest" with conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: pytest -v
