name: Run pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./.github/workflows/environment.yml
    - name: Run "pytest" with conda environment
      run: |
           conda init bash
           conda list
           conda activate base
           conda run python setup.py install
           conda run pytest -v
